// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPISample.Data;

namespace WebAPISample.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20200903015213_initPlot")]
    partial class initPlot
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebAPISample.Models.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Director")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlotSynop")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PosterImageId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MovieId");

                    b.HasIndex("PosterImageId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            Director = "Martin Scorsese",
                            Genre = "Drama",
                            PlotSynop = "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
                            PosterImageId = 1,
                            Title = "The Departed"
                        },
                        new
                        {
                            MovieId = 2,
                            Director = "Christopher Nolan",
                            Genre = "Drama",
                            PosterImageId = 2,
                            Title = "The Dark Knight"
                        },
                        new
                        {
                            MovieId = 3,
                            Director = "Christopher Nolan",
                            Genre = "Drama",
                            PosterImageId = 3,
                            Title = "Inception"
                        },
                        new
                        {
                            MovieId = 4,
                            Director = "David Gordon Green",
                            Genre = "Comedy",
                            PosterImageId = 4,
                            Title = "Pineapple Express"
                        },
                        new
                        {
                            MovieId = 5,
                            Director = "John McTiernan",
                            Genre = "Action",
                            PosterImageId = 5,
                            Title = "Die Hard"
                        },
                        new
                        {
                            MovieId = 6,
                            Director = "Takashii Miike",
                            Genre = "Suspense",
                            PosterImageId = 6,
                            Title = "Audition"
                        },
                        new
                        {
                            MovieId = 7,
                            Director = "Takashii Miike",
                            Genre = "Musical",
                            PosterImageId = 7,
                            Title = "Happieness of the Katakuri"
                        },
                        new
                        {
                            MovieId = 8,
                            Director = "Eric Till",
                            Genre = "Comedy",
                            PosterImageId = 8,
                            Title = "Red Green: Duct Tape Forever"
                        },
                        new
                        {
                            MovieId = 9,
                            Director = "Norman Jewison",
                            Genre = "Comedy",
                            PosterImageId = 9,
                            Title = "Send Me No Flowers"
                        },
                        new
                        {
                            MovieId = 10,
                            Director = "Joe Johnston",
                            Genre = "Action",
                            PosterImageId = 10,
                            Title = "Captain America: The First Avenger"
                        },
                        new
                        {
                            MovieId = 11,
                            Director = "Johnathan Lynn",
                            Genre = "Comedy",
                            PosterImageId = 11,
                            Title = "Clue"
                        },
                        new
                        {
                            MovieId = 12,
                            Director = "Stanley Donen",
                            Genre = "Comedy",
                            PosterImageId = 12,
                            Title = "The Grass is Greener"
                        },
                        new
                        {
                            MovieId = 13,
                            Director = "JBlake Edwards",
                            Genre = "Comedy",
                            PosterImageId = 13,
                            Title = "Operation Petticoat"
                        },
                        new
                        {
                            MovieId = 14,
                            Director = "Adam Mckay",
                            Genre = "Comedy",
                            PosterImageId = 14,
                            Title = "Step Brothers"
                        },
                        new
                        {
                            MovieId = 15,
                            Director = "Kar-Wai Wong",
                            Genre = "Comedy",
                            PosterImageId = 15,
                            Title = "Fallen Angels"
                        });
                });

            modelBuilder.Entity("WebAPISample.Models.PosterImage", b =>
                {
                    b.Property<int>("PosterImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("ImageData")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("PosterLink")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PosterImageId");

                    b.ToTable("PosterImages");

                    b.HasData(
                        new
                        {
                            PosterImageId = 1,
                            PosterLink = "https://m.media-amazon.com/images/M/MV5BMTI1MTY2OTIxNV5BMl5BanBnXkFtZTYwNjQ4NjY3._V1_UX182_CR0,0,182,268_AL_.jpg"
                        },
                        new
                        {
                            PosterImageId = 2,
                            PosterLink = "https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@.jpg"
                        },
                        new
                        {
                            PosterImageId = 3,
                            PosterLink = "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@.jpg"
                        },
                        new
                        {
                            PosterImageId = 4,
                            PosterLink = "https://m.media-amazon.com/images/M/MV5BMTY1MTE4NzAwM15BMl5BanBnXkFtZTcwNzg3Mjg2MQ@@.jpg"
                        },
                        new
                        {
                            PosterImageId = 5,
                            PosterLink = "https://upload.wikimedia.org/wikipedia/en/thumb/7/7e/Die_hard.jpg/220px-Die_hard.jpg"
                        },
                        new
                        {
                            PosterImageId = 6,
                            PosterLink = "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQDYhcR0JMTbmMm_mWMWz0TLiWoQVID1OzxFpeNJFdwWeXaFfCi"
                        },
                        new
                        {
                            PosterImageId = 7,
                            PosterLink = "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRJgAtTCY5coGTbYcV7u7mAhOF3AnqAjNgQ5p1F4U2zPgHM7OWL"
                        },
                        new
                        {
                            PosterImageId = 8,
                            PosterLink = "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSApgxdRebrwCpfIuOfEgnt-2Z9dpzmL1AbfNL-URRMHT61sR0s"
                        },
                        new
                        {
                            PosterImageId = 9,
                            PosterLink = "https://images-na.ssl-images-amazon.com/images/I/91BzjcKK2LL._SX300_.jpg"
                        },
                        new
                        {
                            PosterImageId = 10,
                            PosterLink = "https://images-na.ssl-images-amazon.com/images/I/71GFtflAraL._SX342_.jpg"
                        },
                        new
                        {
                            PosterImageId = 11,
                            PosterLink = "https://m.media-amazon.com/images/I/71ubsh+w3SL._AC_UY218_.jpg"
                        },
                        new
                        {
                            PosterImageId = 12,
                            PosterLink = "https://images-na.ssl-images-amazon.com/images/I/81CtYSap47L._SX300_.jpg"
                        },
                        new
                        {
                            PosterImageId = 13,
                            PosterLink = "https://images-na.ssl-images-amazon.com/images/I/711v2xMuaGL._SX300_.jpg"
                        },
                        new
                        {
                            PosterImageId = 14,
                            PosterLink = "https://images-na.ssl-images-amazon.com/images/I/81SGtfOBoSL._SY445_.jpg"
                        },
                        new
                        {
                            PosterImageId = 15,
                            PosterLink = "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTm4JbHKXxlyPZiBwzBwQVmHq91tX9OuyvHbgDuhvODcHgZcyBN"
                        });
                });

            modelBuilder.Entity("WebAPISample.Models.Movie", b =>
                {
                    b.HasOne("WebAPISample.Models.PosterImage", "PosterImage")
                        .WithMany()
                        .HasForeignKey("PosterImageId");
                });
#pragma warning restore 612, 618
        }
    }
}
