// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPISample.Data;

namespace WebAPISample.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebAPISample.Models.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Director")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PosterImageId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MovieId");

                    b.HasIndex("PosterImageId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            Director = "Martin Scorsese",
                            Genre = "Drama",
                            PosterImageId = 1,
                            Title = "The Departed"
                        },
                        new
                        {
                            MovieId = 2,
                            Director = "Christopher Nolan",
                            Genre = "Drama",
                            PosterImageId = 2,
                            Title = "The Dark Knight"
                        },
                        new
                        {
                            MovieId = 3,
                            Director = "Christopher Nolan",
                            Genre = "Drama",
                            PosterImageId = 3,
                            Title = "Inception"
                        },
                        new
                        {
                            MovieId = 4,
                            Director = "David Gordon Green",
                            Genre = "Comedy",
                            PosterImageId = 4,
                            Title = "Pineapple Express"
                        },
                        new
                        {
                            MovieId = 5,
                            Director = "John McTiernan",
                            Genre = "Action",
                            Title = "Die Hard"
                        },
                        new
                        {
                            MovieId = 6,
                            Director = "Takashii Miike",
                            Genre = "Suspense",
                            Title = "Audition"
                        },
                        new
                        {
                            MovieId = 7,
                            Director = "Takashii Miike",
                            Genre = "Musical",
                            Title = "Happieness of the Katakuri"
                        },
                        new
                        {
                            MovieId = 8,
                            Director = "Eric Till",
                            Genre = "Comedy",
                            Title = "Red Green: Duct Tape Forever"
                        },
                        new
                        {
                            MovieId = 9,
                            Director = "Norman Jewison",
                            Genre = "Comedy",
                            Title = "Send Me No Flowers"
                        },
                        new
                        {
                            MovieId = 10,
                            Director = "Joe Johnston",
                            Genre = "Action",
                            Title = "Captain America: The First Avenger"
                        },
                        new
                        {
                            MovieId = 11,
                            Director = "Johnathan Lynn",
                            Genre = "Comedy",
                            Title = "Clue"
                        },
                        new
                        {
                            MovieId = 12,
                            Director = "Stanley Donen",
                            Genre = "Comedy",
                            Title = "The Grass is Greener"
                        },
                        new
                        {
                            MovieId = 13,
                            Director = "JBlake Edwards",
                            Genre = "Comedy",
                            Title = "Operation Petticoat"
                        },
                        new
                        {
                            MovieId = 14,
                            Director = "Adam Mckay",
                            Genre = "Comedy",
                            Title = "Step Brothers"
                        },
                        new
                        {
                            MovieId = 15,
                            Director = "Kar-Wai Wong",
                            Genre = "Comedy",
                            Title = "Fallen Angels"
                        });
                });

            modelBuilder.Entity("WebAPISample.Models.PosterImage", b =>
                {
                    b.Property<int>("PosterImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("ImageData")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("PosterLink")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PosterImageId");

                    b.ToTable("PosterImages");

                    b.HasData(
                        new
                        {
                            PosterImageId = 1,
                            PosterLink = "https://m.media-amazon.com/images/M/MV5BZjRlNDUxZjAtOGQ4OC00OTNlLTgxNmQtYTBmMDgwZmNmNjkxXkEyXkFqcGdeQXVyNzkwMjQ5NzM@.jpg"
                        },
                        new
                        {
                            PosterImageId = 2,
                            PosterLink = "https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@.jpg"
                        },
                        new
                        {
                            PosterImageId = 3,
                            PosterLink = "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@.jpg"
                        },
                        new
                        {
                            PosterImageId = 4,
                            PosterLink = "https://m.media-amazon.com/images/M/MV5BMTY1MTE4NzAwM15BMl5BanBnXkFtZTcwNzg3Mjg2MQ@@.jpg"
                        });
                });

            modelBuilder.Entity("WebAPISample.Models.Movie", b =>
                {
                    b.HasOne("WebAPISample.Models.PosterImage", "PosterImage")
                        .WithMany()
                        .HasForeignKey("PosterImageId");
                });
#pragma warning restore 612, 618
        }
    }
}
